---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Antes de fazer `to_datetime`, os valores na coluna `date` eram do tipo `object`.
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Antes de fazer `to_datetime`, os valores na coluna `date` eram do tipo `datetime64`.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Depois de fazer `to_datetime`, os valores da coluna `date` são do tipo `object`.
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Depois de fazer `to_datetime`, os valores da coluna `date` são do tipo `datetime64`.
  checked: true
name: Reserve a data
