---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`loc_code`"
  checked: false
- value: "`obs`"
  checked: true
- value: "`category`"
  checked: true
- value: "`province`"
  checked: false
- value: "`department`"
  checked: false
- value: "`city`"
  checked: false
- value: "`name`"
  checked: false
- value: "`address`"
  checked: false
- value: "`update_year`"
  checked: true
name: Você sim, você não
