---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Em `cruzeiristas` não há colunas que precisem ser transformadas com `to_numeric`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se aplicarmos `to_numeric` em uma `Series` que contém apenas números, falhará
    com um `ValueError`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se aplicarmos `to_numeric` em uma `Series` que contém apenas números, retornará
    uma cópia com os mesmos valores
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se aplicarmos `to_numeric` em uma `Series` que contém strings não numéricas,
    falhará com um `ValueError`
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Se aplicarmos `to_numeric` em uma `Series` que contém números e strings numéricas,
    falhará com um `ValueError`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: '`numeros_mentirosos` + `numeros_mentirosos` retorna uma `Series` com os
    valores `"44"`, `"99"` e `"88"`'
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`pd.to_numeric(numeros_mentirosos) * 2 ` retorna uma `Series` com os valores
    `8`, `18` e `16`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`to_numeric` modifica a `Series` original"
  checked: false
name: Os números pelo seu nome
