import numpy as np
import pandas as pd

cines = pd.DataFrame(
  [{'loc_code': 6861010, 'prov_id': 6, 'dep_id': 6861, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Vicente Lopez', 'city': 'Munro', 'name': 'Lumiton', 'address': 'Sargento Cabral 2354', 'floor': 's/d', 'zip_code': 1605, 'area_code': 's/d', 'sector': 'Público municipal', 'screens': 1, 'seats': 30, 'update_year': 2018},
 {'loc_code': 34014020, 'prov_id': 34, 'dep_id': 34014, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Formosa', 'department': 'Formosa', 'city': 'Formosa', 'name': 'Cine Teatro Italia', 'address': 'Av. 25 De Mayo 353', 'floor': 's/d', 'zip_code': 3600, 'area_code': '3717', 'sector': 'Público provincial', 'screens': 1, 'seats': 565, 'update_year': 2018},
 {'loc_code': 82049020, 'prov_id': 82, 'dep_id': 82049, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Santa Fe', 'department': 'General Obligado', 'city': 'Avellaneda', 'name': 'Luna De Avellaneda', 'address': 'Av. San Martin 810', 'floor': 's/d', 'zip_code': 3561, 'area_code': '3482', 'sector': 'Privado comercial', 'screens': 1, 'seats': 299, 'update_year': 2018},
 {'loc_code': 6441030, 'prov_id': 6, 'dep_id': 6441, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'La Plata', 'city': 'La Plata', 'name': 'Cinema Paraíso', 'address': 'Calle 46 780', 'floor': 's/d', 'zip_code': 1900, 'area_code': '221', 'sector': 'Privado comercial', 'screens': 4, 'seats': 603, 'update_year': 2018},
 {'loc_code': 30049040, 'prov_id': 30, 'dep_id': 30049, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Entre Ríos', 'department': 'Gualeguay', 'city': 'Gualeguay', 'name': 'Altos Del Gualeguay', 'address': 'Rocamora 33', 'floor': 's/d', 'zip_code': 2840, 'area_code': '3444', 'sector': 'Privado comercial', 'screens': 1, 'seats': 198, 'update_year': 2018},
 {'loc_code': 6420040, 'prov_id': 6, 'dep_id': 6420, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'La Costa', 'city': 'Santa Teresita', 'name': 'Atlántico', 'address': 'Calle 41 258', 'floor': 's/d', 'zip_code': 7107, 'area_code': '224', 'sector': 'Privado comercial', 'screens': 1, 'seats': 1107, 'update_year': 2018},
 {'loc_code': 30084160, 'prov_id': 30, 'dep_id': 30084, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Entre Ríos', 'department': 'Parana', 'city': 'Paraná', 'name': 'Cine Rex', 'address': 'Monte Caseros 266', 'floor': 's/d', 'zip_code': 3100, 'area_code': '343', 'sector': 'Privado comercial', 'screens': 3, 'seats': 434, 'update_year': 2018},
 {'loc_code': 6595070, 'prov_id': 6, 'dep_id': 6595, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Olavarria', 'city': 'Olavarría', 'name': 'Cine Paris', 'address': 'General Paz 2720', 'floor': 's/d', 'zip_code': 7400, 'area_code': '2284', 'sector': 'Privado comercial', 'screens': 2, 'seats': 383, 'update_year': 2018},
 {'loc_code': 10049030, 'prov_id': 10, 'dep_id': 10049, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Catamarca', 'department': 'Capital', 'city': 'Catamarca', 'name': 'Cinemacenter', 'address': 'Av. Guemes 850', 'floor': 's/d', 'zip_code': 4700, 'area_code': '3833', 'sector': 'Privado comercial', 'screens': 5, 'seats': 914, 'update_year': 2018},
 {'loc_code': 6805010, 'prov_id': 6, 'dep_id': 6805, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Tigre', 'city': 'Rincón de Milberg', 'name': 'Nordel Cinema', 'address': 'Av. De Los Lagos 7010', 'floor': 's/d', 'zip_code': 1617, 'area_code': 's/d', 'sector': 'Privado comercial', 'screens': 5, 'seats': 969, 'update_year': 2018}])