---
locale: pt
tags: []
layout: input_bottom
editor: external
type: problem
extra_visible: false
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices: []
name: Novo nome, nova vida
