---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`loc_code`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`obs`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`category`"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`province`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`department`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`city`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`name`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`address`"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`update_year`"
  checked: true
name: Vos sí, vos no
